export default [
    {
        _id: '66ba098591ad6c4cfda86fc4',
        isActive: true,
        age: 27,
        name: 'Pate Hurley',
        gender: 'male',
        company: 'VINCH',
        email: 'patehurley@vinch.com',
        phone: '+1 (876) 482-3826',
        address: '831 Lake Avenue, Bluffview, West Virginia, 7651',
        about: 'Commodo proident labore aliqua laborum officia proident laborum. Mollit ea amet cupidatat sit consectetur aliqua deserunt ullamco veniam ipsum velit ex et. Ullamco nulla enim in culpa elit aliquip duis excepteur. Sunt ipsum elit eu amet et ex ex ipsum proident dolore cupidatat. Ut in tempor et aliqua. Velit ut irure labore enim minim elit voluptate eiusmod Lorem cillum ea sunt.\r\n',
        registered: '2021-09-10T05:18:25 -03:00',
    },
    {
        _id: '66ba09855b86d935582a5f6c',
        isActive: false,
        age: 24,
        name: 'Taylor Underwood',
        gender: 'female',
        company: 'EZENT',
        email: 'taylorunderwood@ezent.com',
        phone: '+1 (904) 512-2680',
        address: '533 Newkirk Avenue, Norvelt, Michigan, 7660',
        about: 'Exercitation aliqua esse ut deserunt cupidatat consectetur labore. Cillum ad occaecat officia exercitation. Ullamco sint duis commodo nulla aliquip nulla culpa tempor veniam reprehenderit ex eu laborum. Eu esse excepteur minim do in duis duis aute aute elit.\r\n',
        registered: '2019-06-28T12:22:55 -03:00',
    },
    {
        _id: '66ba0985a8e331074db5f4ea',
        isActive: false,
        age: 39,
        name: 'Earline Cross',
        gender: 'female',
        company: 'ZIDANT',
        email: 'earlinecross@zidant.com',
        phone: '+1 (916) 595-3812',
        address: '159 Laurel Avenue, Idledale, Texas, 2653',
        about: 'Consectetur elit officia exercitation non dolor enim pariatur. Id enim adipisicing nulla in. Non proident excepteur sit ad minim dolore laborum velit. Aliquip aute consequat proident magna. Fugiat laboris sint magna ad. Magna voluptate esse Lorem Lorem. Cupidatat Lorem labore culpa cillum adipisicing labore est qui.\r\n',
        registered: '2014-12-07T11:16:00 -02:00',
    },
    {
        _id: '66ba09854efc8bed02a3316a',
        isActive: true,
        age: 26,
        name: 'Cornelia Burks',
        gender: 'female',
        company: 'STREZZO',
        email: 'corneliaburks@strezzo.com',
        phone: '+1 (879) 539-2938',
        address: '729 Ash Street, Chumuckla, Colorado, 7858',
        about: 'Irure enim occaecat non exercitation culpa sit magna in ea dolore enim. Anim aliquip sit irure dolor fugiat fugiat adipisicing. Eiusmod ipsum mollit occaecat ex veniam officia aliqua. Quis mollit anim fugiat consequat enim ipsum quis id est incididunt consequat aute. Officia sint cupidatat aute sint minim reprehenderit velit non voluptate et occaecat sunt velit.\r\n',
        registered: '2023-02-05T06:19:37 -02:00',
    },
    {
        _id: '66ba09857ffca7ebc6473f5a',
        isActive: true,
        age: 38,
        name: 'Cain Valentine',
        gender: 'male',
        company: 'ACCEL',
        email: 'cainvalentine@accel.com',
        phone: '+1 (857) 445-3431',
        address: '325 Oceanview Avenue, Drytown, Delaware, 7550',
        about: 'Exercitation esse officia aliquip non nostrud qui voluptate ad quis do aliqua. Magna Lorem veniam incididunt labore dolore veniam nisi Lorem. Tempor duis voluptate cillum ex Lorem. Reprehenderit nostrud voluptate amet adipisicing ullamco dolor ea non ad dolore.\r\n',
        registered: '2023-04-06T10:45:53 -03:00',
    },
    {
        _id: '66ba0985d228eecf37e5c161',
        isActive: true,
        age: 40,
        name: 'Brady Stephens',
        gender: 'male',
        company: 'MOTOVATE',
        email: 'bradystephens@motovate.com',
        phone: '+1 (946) 502-2256',
        address: '835 Lake Street, Brambleton, Vermont, 6033',
        about: 'Quis ipsum irure officia exercitation exercitation irure irure fugiat irure irure pariatur. Cillum sunt id eiusmod ea voluptate quis voluptate pariatur nulla proident elit labore aute Lorem. Incididunt incididunt et ipsum ut eu qui ullamco.\r\n',
        registered: '2014-08-11T04:55:12 -03:00',
    },
    {
        _id: '66ba09859cd672b214ecffbe',
        isActive: true,
        age: 20,
        name: 'Nora Holland',
        gender: 'female',
        company: 'CALCULA',
        email: 'noraholland@calcula.com',
        phone: '+1 (877) 452-3840',
        address: '141 Joval Court, Enetai, Virginia, 4686',
        about: 'Dolor labore eu sit et minim cillum aute do non enim. Sint quis elit amet et ullamco in eiusmod et sit laboris aute duis dolor minim. Ad Lorem magna Lorem nostrud officia ex magna tempor. Laboris quis enim reprehenderit ipsum duis.\r\n',
        registered: '2018-07-06T05:49:38 -03:00',
    },
];
